FROM python:3.7-alpine

# Copia os arquivos para o diretório /app
COPY . /app 
# Define o diretório de trabalho
WORKDIR /app

# Instala as dependências
RUN pip install -r Requirements.txt

# Define o comando que será executado quando o contêiner iniciar


